version: "3"
services:
  docker-nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  docker-node-app:
    build: .
    environment:
      - PORT=3000
    depends_on:
      - docker-mongo

  docker-mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=sanjeev
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - mongo-db:/data/db

  docker-redis:
    image: redis

volumes:
  mongo-db: