version: "3"
services:
  docker-nginx:
    ports:
      - "3000:80"

  docker-node-app:
    build:
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - .:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=sanjeev
      - MONGO_PASSWORD=mypassword
      - MONGO_IP=docker-mongo
      - MONGO_PORT=27017
      - SESSION_SECRET=secret
    command: npm run dev

  docker-mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=sanjeev
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db: