version: "3"
services:
  docker-nginx:
    ports:
      - "3000:80"

  docker-node-app:
    build:
      context: .
      args:
        - NODE_ENV=production
    environment:
      - NODE_ENV=production
    command: npm start